name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login verosteam.jfrog.com -u ${{ secrets.JFROG_USERNAME }} -p ${{secrets.JFROG_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag verosteam.jfrog.io/docker/my-docker-image:latest
    - name: Push the Docker image
      run: docker push verosteam.jfrog.io/docker/my-docker-image:latest
